// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// APICredentials ApiCredentials
// swagger:model ApiCredentials
type APICredentials struct {

	// basic
	Basic *Basic `json:"basic,omitempty"`

	// certificate gen
	CertificateGen *CertificateGen `json:"certificateGen,omitempty"`

	// Additional headers to be injected during auth requests
	Headers map[string]interface{} `json:"headers,omitempty"`

	// oauth
	Oauth *OAuth `json:"oauth,omitempty"`

	// Additional query parameters to be injected during auth requests
	QueryParameters map[string]interface{} `json:"queryParameters,omitempty"`
}

// Validate validates this Api credentials
func (m *APICredentials) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBasic(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCertificateGen(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOauth(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APICredentials) validateBasic(formats strfmt.Registry) error {

	if swag.IsZero(m.Basic) { // not required
		return nil
	}

	if m.Basic != nil {
		if err := m.Basic.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("basic")
			}
			return err
		}
	}

	return nil
}

func (m *APICredentials) validateCertificateGen(formats strfmt.Registry) error {

	if swag.IsZero(m.CertificateGen) { // not required
		return nil
	}

	if m.CertificateGen != nil {
		if err := m.CertificateGen.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("certificateGen")
			}
			return err
		}
	}

	return nil
}

func (m *APICredentials) validateOauth(formats strfmt.Registry) error {

	if swag.IsZero(m.Oauth) { // not required
		return nil
	}

	if m.Oauth != nil {
		if err := m.Oauth.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("oauth")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APICredentials) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APICredentials) UnmarshalBinary(b []byte) error {
	var res APICredentials
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
