// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CertificateGenUpdate CertificateGenUpdate
// swagger:model CertificateGenUpdate
type CertificateGenUpdate struct {

	// common name
	CommonName string `json:"commonName,omitempty"`
}

// Validate validates this certificate gen update
func (m *CertificateGenUpdate) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CertificateGenUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CertificateGenUpdate) UnmarshalBinary(b []byte) error {
	var res CertificateGenUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
