// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// RequestParameters request parameters
// swagger:model RequestParameters
type RequestParameters struct {

	// Additional headers to be injected during auth requests
	Headers map[string][]string `json:"headers,omitempty"`

	// Additional query parameters to be injected during auth requests
	QueryParameters map[string][]string `json:"queryParameters,omitempty"`
}

// Validate validates this request parameters
func (m *RequestParameters) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestParameters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestParameters) UnmarshalBinary(b []byte) error {
	var res RequestParameters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
