// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TraceLoggingConfig trace logging config
// swagger:model TraceLoggingConfig
type TraceLoggingConfig struct {

	// The duration, in minutes, to enable trace-level logging for. Defaults to 30 minutes.
	Duration int64 `json:"duration,omitempty"`
}

// Validate validates this trace logging config
func (m *TraceLoggingConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TraceLoggingConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TraceLoggingConfig) UnmarshalBinary(b []byte) error {
	var res TraceLoggingConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
