// Code generated by go-swagger; DO NOT EDIT.

package instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/akrausesap/goexperiments/openconnectors/util/connectorclient/models"
)

// NewCreateInstanceObjectObjectNameDefinitionParams creates a new CreateInstanceObjectObjectNameDefinitionParams object
// with the default values initialized.
func NewCreateInstanceObjectObjectNameDefinitionParams() *CreateInstanceObjectObjectNameDefinitionParams {
	var ()
	return &CreateInstanceObjectObjectNameDefinitionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateInstanceObjectObjectNameDefinitionParamsWithTimeout creates a new CreateInstanceObjectObjectNameDefinitionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateInstanceObjectObjectNameDefinitionParamsWithTimeout(timeout time.Duration) *CreateInstanceObjectObjectNameDefinitionParams {
	var ()
	return &CreateInstanceObjectObjectNameDefinitionParams{

		timeout: timeout,
	}
}

// NewCreateInstanceObjectObjectNameDefinitionParamsWithContext creates a new CreateInstanceObjectObjectNameDefinitionParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateInstanceObjectObjectNameDefinitionParamsWithContext(ctx context.Context) *CreateInstanceObjectObjectNameDefinitionParams {
	var ()
	return &CreateInstanceObjectObjectNameDefinitionParams{

		Context: ctx,
	}
}

// NewCreateInstanceObjectObjectNameDefinitionParamsWithHTTPClient creates a new CreateInstanceObjectObjectNameDefinitionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateInstanceObjectObjectNameDefinitionParamsWithHTTPClient(client *http.Client) *CreateInstanceObjectObjectNameDefinitionParams {
	var ()
	return &CreateInstanceObjectObjectNameDefinitionParams{
		HTTPClient: client,
	}
}

/*CreateInstanceObjectObjectNameDefinitionParams contains all the parameters to send to the API endpoint
for the create instance object object name definition operation typically these are written to a http.Request
*/
type CreateInstanceObjectObjectNameDefinitionParams struct {

	/*Authorization
	  The authorization tokens. The format for the header value is 'User &lt;user secret&gt;, Organization &lt;org secret&gt;, Element &lt;token&gt;'

	*/
	Authorization string
	/*Body
	  The object definition

	*/
	Body *models.Definition
	/*ObjectName
	  The name of the object

	*/
	ObjectName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create instance object object name definition params
func (o *CreateInstanceObjectObjectNameDefinitionParams) WithTimeout(timeout time.Duration) *CreateInstanceObjectObjectNameDefinitionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create instance object object name definition params
func (o *CreateInstanceObjectObjectNameDefinitionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create instance object object name definition params
func (o *CreateInstanceObjectObjectNameDefinitionParams) WithContext(ctx context.Context) *CreateInstanceObjectObjectNameDefinitionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create instance object object name definition params
func (o *CreateInstanceObjectObjectNameDefinitionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create instance object object name definition params
func (o *CreateInstanceObjectObjectNameDefinitionParams) WithHTTPClient(client *http.Client) *CreateInstanceObjectObjectNameDefinitionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create instance object object name definition params
func (o *CreateInstanceObjectObjectNameDefinitionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the create instance object object name definition params
func (o *CreateInstanceObjectObjectNameDefinitionParams) WithAuthorization(authorization string) *CreateInstanceObjectObjectNameDefinitionParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the create instance object object name definition params
func (o *CreateInstanceObjectObjectNameDefinitionParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBody adds the body to the create instance object object name definition params
func (o *CreateInstanceObjectObjectNameDefinitionParams) WithBody(body *models.Definition) *CreateInstanceObjectObjectNameDefinitionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create instance object object name definition params
func (o *CreateInstanceObjectObjectNameDefinitionParams) SetBody(body *models.Definition) {
	o.Body = body
}

// WithObjectName adds the objectName to the create instance object object name definition params
func (o *CreateInstanceObjectObjectNameDefinitionParams) WithObjectName(objectName string) *CreateInstanceObjectObjectNameDefinitionParams {
	o.SetObjectName(objectName)
	return o
}

// SetObjectName adds the objectName to the create instance object object name definition params
func (o *CreateInstanceObjectObjectNameDefinitionParams) SetObjectName(objectName string) {
	o.ObjectName = objectName
}

// WriteToRequest writes these params to a swagger request
func (o *CreateInstanceObjectObjectNameDefinitionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param objectName
	if err := r.SetPathParam("objectName", o.ObjectName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
