// Code generated by go-swagger; DO NOT EDIT.

package instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/akrausesap/goexperiments/openconnectors/util/connectorclient/models"
)

// CreateInstanceTransformationByObjectNameReader is a Reader for the CreateInstanceTransformationByObjectName structure.
type CreateInstanceTransformationByObjectNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateInstanceTransformationByObjectNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateInstanceTransformationByObjectNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateInstanceTransformationByObjectNameBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewCreateInstanceTransformationByObjectNameUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewCreateInstanceTransformationByObjectNameForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewCreateInstanceTransformationByObjectNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewCreateInstanceTransformationByObjectNameMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 406:
		result := NewCreateInstanceTransformationByObjectNameNotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewCreateInstanceTransformationByObjectNameConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 415:
		result := NewCreateInstanceTransformationByObjectNameUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewCreateInstanceTransformationByObjectNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateInstanceTransformationByObjectNameOK creates a CreateInstanceTransformationByObjectNameOK with default headers values
func NewCreateInstanceTransformationByObjectNameOK() *CreateInstanceTransformationByObjectNameOK {
	return &CreateInstanceTransformationByObjectNameOK{}
}

/*CreateInstanceTransformationByObjectNameOK handles this case with default header values.

OK - Everything worked as expected
*/
type CreateInstanceTransformationByObjectNameOK struct {
	Payload *models.Transformation
}

func (o *CreateInstanceTransformationByObjectNameOK) Error() string {
	return fmt.Sprintf("[POST /instances/transformations/{objectName}][%d] createInstanceTransformationByObjectNameOK  %+v", 200, o.Payload)
}

func (o *CreateInstanceTransformationByObjectNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Transformation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateInstanceTransformationByObjectNameBadRequest creates a CreateInstanceTransformationByObjectNameBadRequest with default headers values
func NewCreateInstanceTransformationByObjectNameBadRequest() *CreateInstanceTransformationByObjectNameBadRequest {
	return &CreateInstanceTransformationByObjectNameBadRequest{}
}

/*CreateInstanceTransformationByObjectNameBadRequest handles this case with default header values.

Bad Request - Often due to a missing request parameter
*/
type CreateInstanceTransformationByObjectNameBadRequest struct {
}

func (o *CreateInstanceTransformationByObjectNameBadRequest) Error() string {
	return fmt.Sprintf("[POST /instances/transformations/{objectName}][%d] createInstanceTransformationByObjectNameBadRequest ", 400)
}

func (o *CreateInstanceTransformationByObjectNameBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateInstanceTransformationByObjectNameUnauthorized creates a CreateInstanceTransformationByObjectNameUnauthorized with default headers values
func NewCreateInstanceTransformationByObjectNameUnauthorized() *CreateInstanceTransformationByObjectNameUnauthorized {
	return &CreateInstanceTransformationByObjectNameUnauthorized{}
}

/*CreateInstanceTransformationByObjectNameUnauthorized handles this case with default header values.

Unauthorized - An invalid element token, user secret and/or org secret provided
*/
type CreateInstanceTransformationByObjectNameUnauthorized struct {
}

func (o *CreateInstanceTransformationByObjectNameUnauthorized) Error() string {
	return fmt.Sprintf("[POST /instances/transformations/{objectName}][%d] createInstanceTransformationByObjectNameUnauthorized ", 401)
}

func (o *CreateInstanceTransformationByObjectNameUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateInstanceTransformationByObjectNameForbidden creates a CreateInstanceTransformationByObjectNameForbidden with default headers values
func NewCreateInstanceTransformationByObjectNameForbidden() *CreateInstanceTransformationByObjectNameForbidden {
	return &CreateInstanceTransformationByObjectNameForbidden{}
}

/*CreateInstanceTransformationByObjectNameForbidden handles this case with default header values.

Forbidden - Access to the resource by the provider is forbidden
*/
type CreateInstanceTransformationByObjectNameForbidden struct {
}

func (o *CreateInstanceTransformationByObjectNameForbidden) Error() string {
	return fmt.Sprintf("[POST /instances/transformations/{objectName}][%d] createInstanceTransformationByObjectNameForbidden ", 403)
}

func (o *CreateInstanceTransformationByObjectNameForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateInstanceTransformationByObjectNameNotFound creates a CreateInstanceTransformationByObjectNameNotFound with default headers values
func NewCreateInstanceTransformationByObjectNameNotFound() *CreateInstanceTransformationByObjectNameNotFound {
	return &CreateInstanceTransformationByObjectNameNotFound{}
}

/*CreateInstanceTransformationByObjectNameNotFound handles this case with default header values.

Not found - The requested resource is not found
*/
type CreateInstanceTransformationByObjectNameNotFound struct {
}

func (o *CreateInstanceTransformationByObjectNameNotFound) Error() string {
	return fmt.Sprintf("[POST /instances/transformations/{objectName}][%d] createInstanceTransformationByObjectNameNotFound ", 404)
}

func (o *CreateInstanceTransformationByObjectNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateInstanceTransformationByObjectNameMethodNotAllowed creates a CreateInstanceTransformationByObjectNameMethodNotAllowed with default headers values
func NewCreateInstanceTransformationByObjectNameMethodNotAllowed() *CreateInstanceTransformationByObjectNameMethodNotAllowed {
	return &CreateInstanceTransformationByObjectNameMethodNotAllowed{}
}

/*CreateInstanceTransformationByObjectNameMethodNotAllowed handles this case with default header values.

Method not allowed - Incorrect HTTP verb used, e.g., GET used when POST expected
*/
type CreateInstanceTransformationByObjectNameMethodNotAllowed struct {
}

func (o *CreateInstanceTransformationByObjectNameMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /instances/transformations/{objectName}][%d] createInstanceTransformationByObjectNameMethodNotAllowed ", 405)
}

func (o *CreateInstanceTransformationByObjectNameMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateInstanceTransformationByObjectNameNotAcceptable creates a CreateInstanceTransformationByObjectNameNotAcceptable with default headers values
func NewCreateInstanceTransformationByObjectNameNotAcceptable() *CreateInstanceTransformationByObjectNameNotAcceptable {
	return &CreateInstanceTransformationByObjectNameNotAcceptable{}
}

/*CreateInstanceTransformationByObjectNameNotAcceptable handles this case with default header values.

Not acceptable - The response content type does not match the 'Accept' header value
*/
type CreateInstanceTransformationByObjectNameNotAcceptable struct {
}

func (o *CreateInstanceTransformationByObjectNameNotAcceptable) Error() string {
	return fmt.Sprintf("[POST /instances/transformations/{objectName}][%d] createInstanceTransformationByObjectNameNotAcceptable ", 406)
}

func (o *CreateInstanceTransformationByObjectNameNotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateInstanceTransformationByObjectNameConflict creates a CreateInstanceTransformationByObjectNameConflict with default headers values
func NewCreateInstanceTransformationByObjectNameConflict() *CreateInstanceTransformationByObjectNameConflict {
	return &CreateInstanceTransformationByObjectNameConflict{}
}

/*CreateInstanceTransformationByObjectNameConflict handles this case with default header values.

Conflict - If a resource being created already exists
*/
type CreateInstanceTransformationByObjectNameConflict struct {
}

func (o *CreateInstanceTransformationByObjectNameConflict) Error() string {
	return fmt.Sprintf("[POST /instances/transformations/{objectName}][%d] createInstanceTransformationByObjectNameConflict ", 409)
}

func (o *CreateInstanceTransformationByObjectNameConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateInstanceTransformationByObjectNameUnsupportedMediaType creates a CreateInstanceTransformationByObjectNameUnsupportedMediaType with default headers values
func NewCreateInstanceTransformationByObjectNameUnsupportedMediaType() *CreateInstanceTransformationByObjectNameUnsupportedMediaType {
	return &CreateInstanceTransformationByObjectNameUnsupportedMediaType{}
}

/*CreateInstanceTransformationByObjectNameUnsupportedMediaType handles this case with default header values.

Unsupported media type - The server cannot handle the requested Content-Type
*/
type CreateInstanceTransformationByObjectNameUnsupportedMediaType struct {
}

func (o *CreateInstanceTransformationByObjectNameUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[POST /instances/transformations/{objectName}][%d] createInstanceTransformationByObjectNameUnsupportedMediaType ", 415)
}

func (o *CreateInstanceTransformationByObjectNameUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateInstanceTransformationByObjectNameInternalServerError creates a CreateInstanceTransformationByObjectNameInternalServerError with default headers values
func NewCreateInstanceTransformationByObjectNameInternalServerError() *CreateInstanceTransformationByObjectNameInternalServerError {
	return &CreateInstanceTransformationByObjectNameInternalServerError{}
}

/*CreateInstanceTransformationByObjectNameInternalServerError handles this case with default header values.

Server error - Something went wrong on the Cloud Elements server
*/
type CreateInstanceTransformationByObjectNameInternalServerError struct {
}

func (o *CreateInstanceTransformationByObjectNameInternalServerError) Error() string {
	return fmt.Sprintf("[POST /instances/transformations/{objectName}][%d] createInstanceTransformationByObjectNameInternalServerError ", 500)
}

func (o *CreateInstanceTransformationByObjectNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
