// Code generated by go-swagger; DO NOT EDIT.

package instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteInstancesTransformationByObjectNameReader is a Reader for the DeleteInstancesTransformationByObjectName structure.
type DeleteInstancesTransformationByObjectNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteInstancesTransformationByObjectNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteInstancesTransformationByObjectNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteInstancesTransformationByObjectNameBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteInstancesTransformationByObjectNameUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteInstancesTransformationByObjectNameForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteInstancesTransformationByObjectNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewDeleteInstancesTransformationByObjectNameMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 406:
		result := NewDeleteInstancesTransformationByObjectNameNotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewDeleteInstancesTransformationByObjectNameConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 415:
		result := NewDeleteInstancesTransformationByObjectNameUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteInstancesTransformationByObjectNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteInstancesTransformationByObjectNameOK creates a DeleteInstancesTransformationByObjectNameOK with default headers values
func NewDeleteInstancesTransformationByObjectNameOK() *DeleteInstancesTransformationByObjectNameOK {
	return &DeleteInstancesTransformationByObjectNameOK{}
}

/*DeleteInstancesTransformationByObjectNameOK handles this case with default header values.

OK - Everything worked as expected
*/
type DeleteInstancesTransformationByObjectNameOK struct {
}

func (o *DeleteInstancesTransformationByObjectNameOK) Error() string {
	return fmt.Sprintf("[DELETE /instances/transformations/{objectName}][%d] deleteInstancesTransformationByObjectNameOK ", 200)
}

func (o *DeleteInstancesTransformationByObjectNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInstancesTransformationByObjectNameBadRequest creates a DeleteInstancesTransformationByObjectNameBadRequest with default headers values
func NewDeleteInstancesTransformationByObjectNameBadRequest() *DeleteInstancesTransformationByObjectNameBadRequest {
	return &DeleteInstancesTransformationByObjectNameBadRequest{}
}

/*DeleteInstancesTransformationByObjectNameBadRequest handles this case with default header values.

Bad Request - Often due to a missing request parameter
*/
type DeleteInstancesTransformationByObjectNameBadRequest struct {
}

func (o *DeleteInstancesTransformationByObjectNameBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /instances/transformations/{objectName}][%d] deleteInstancesTransformationByObjectNameBadRequest ", 400)
}

func (o *DeleteInstancesTransformationByObjectNameBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInstancesTransformationByObjectNameUnauthorized creates a DeleteInstancesTransformationByObjectNameUnauthorized with default headers values
func NewDeleteInstancesTransformationByObjectNameUnauthorized() *DeleteInstancesTransformationByObjectNameUnauthorized {
	return &DeleteInstancesTransformationByObjectNameUnauthorized{}
}

/*DeleteInstancesTransformationByObjectNameUnauthorized handles this case with default header values.

Unauthorized - An invalid element token, user secret and/or org secret provided
*/
type DeleteInstancesTransformationByObjectNameUnauthorized struct {
}

func (o *DeleteInstancesTransformationByObjectNameUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /instances/transformations/{objectName}][%d] deleteInstancesTransformationByObjectNameUnauthorized ", 401)
}

func (o *DeleteInstancesTransformationByObjectNameUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInstancesTransformationByObjectNameForbidden creates a DeleteInstancesTransformationByObjectNameForbidden with default headers values
func NewDeleteInstancesTransformationByObjectNameForbidden() *DeleteInstancesTransformationByObjectNameForbidden {
	return &DeleteInstancesTransformationByObjectNameForbidden{}
}

/*DeleteInstancesTransformationByObjectNameForbidden handles this case with default header values.

Forbidden - Access to the resource by the provider is forbidden
*/
type DeleteInstancesTransformationByObjectNameForbidden struct {
}

func (o *DeleteInstancesTransformationByObjectNameForbidden) Error() string {
	return fmt.Sprintf("[DELETE /instances/transformations/{objectName}][%d] deleteInstancesTransformationByObjectNameForbidden ", 403)
}

func (o *DeleteInstancesTransformationByObjectNameForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInstancesTransformationByObjectNameNotFound creates a DeleteInstancesTransformationByObjectNameNotFound with default headers values
func NewDeleteInstancesTransformationByObjectNameNotFound() *DeleteInstancesTransformationByObjectNameNotFound {
	return &DeleteInstancesTransformationByObjectNameNotFound{}
}

/*DeleteInstancesTransformationByObjectNameNotFound handles this case with default header values.

Not found - The requested resource is not found
*/
type DeleteInstancesTransformationByObjectNameNotFound struct {
}

func (o *DeleteInstancesTransformationByObjectNameNotFound) Error() string {
	return fmt.Sprintf("[DELETE /instances/transformations/{objectName}][%d] deleteInstancesTransformationByObjectNameNotFound ", 404)
}

func (o *DeleteInstancesTransformationByObjectNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInstancesTransformationByObjectNameMethodNotAllowed creates a DeleteInstancesTransformationByObjectNameMethodNotAllowed with default headers values
func NewDeleteInstancesTransformationByObjectNameMethodNotAllowed() *DeleteInstancesTransformationByObjectNameMethodNotAllowed {
	return &DeleteInstancesTransformationByObjectNameMethodNotAllowed{}
}

/*DeleteInstancesTransformationByObjectNameMethodNotAllowed handles this case with default header values.

Method not allowed - Incorrect HTTP verb used, e.g., GET used when POST expected
*/
type DeleteInstancesTransformationByObjectNameMethodNotAllowed struct {
}

func (o *DeleteInstancesTransformationByObjectNameMethodNotAllowed) Error() string {
	return fmt.Sprintf("[DELETE /instances/transformations/{objectName}][%d] deleteInstancesTransformationByObjectNameMethodNotAllowed ", 405)
}

func (o *DeleteInstancesTransformationByObjectNameMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInstancesTransformationByObjectNameNotAcceptable creates a DeleteInstancesTransformationByObjectNameNotAcceptable with default headers values
func NewDeleteInstancesTransformationByObjectNameNotAcceptable() *DeleteInstancesTransformationByObjectNameNotAcceptable {
	return &DeleteInstancesTransformationByObjectNameNotAcceptable{}
}

/*DeleteInstancesTransformationByObjectNameNotAcceptable handles this case with default header values.

Not acceptable - The response content type does not match the 'Accept' header value
*/
type DeleteInstancesTransformationByObjectNameNotAcceptable struct {
}

func (o *DeleteInstancesTransformationByObjectNameNotAcceptable) Error() string {
	return fmt.Sprintf("[DELETE /instances/transformations/{objectName}][%d] deleteInstancesTransformationByObjectNameNotAcceptable ", 406)
}

func (o *DeleteInstancesTransformationByObjectNameNotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInstancesTransformationByObjectNameConflict creates a DeleteInstancesTransformationByObjectNameConflict with default headers values
func NewDeleteInstancesTransformationByObjectNameConflict() *DeleteInstancesTransformationByObjectNameConflict {
	return &DeleteInstancesTransformationByObjectNameConflict{}
}

/*DeleteInstancesTransformationByObjectNameConflict handles this case with default header values.

Conflict - If a resource being created already exists
*/
type DeleteInstancesTransformationByObjectNameConflict struct {
}

func (o *DeleteInstancesTransformationByObjectNameConflict) Error() string {
	return fmt.Sprintf("[DELETE /instances/transformations/{objectName}][%d] deleteInstancesTransformationByObjectNameConflict ", 409)
}

func (o *DeleteInstancesTransformationByObjectNameConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInstancesTransformationByObjectNameUnsupportedMediaType creates a DeleteInstancesTransformationByObjectNameUnsupportedMediaType with default headers values
func NewDeleteInstancesTransformationByObjectNameUnsupportedMediaType() *DeleteInstancesTransformationByObjectNameUnsupportedMediaType {
	return &DeleteInstancesTransformationByObjectNameUnsupportedMediaType{}
}

/*DeleteInstancesTransformationByObjectNameUnsupportedMediaType handles this case with default header values.

Unsupported media type - The server cannot handle the requested Content-Type
*/
type DeleteInstancesTransformationByObjectNameUnsupportedMediaType struct {
}

func (o *DeleteInstancesTransformationByObjectNameUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[DELETE /instances/transformations/{objectName}][%d] deleteInstancesTransformationByObjectNameUnsupportedMediaType ", 415)
}

func (o *DeleteInstancesTransformationByObjectNameUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInstancesTransformationByObjectNameInternalServerError creates a DeleteInstancesTransformationByObjectNameInternalServerError with default headers values
func NewDeleteInstancesTransformationByObjectNameInternalServerError() *DeleteInstancesTransformationByObjectNameInternalServerError {
	return &DeleteInstancesTransformationByObjectNameInternalServerError{}
}

/*DeleteInstancesTransformationByObjectNameInternalServerError handles this case with default header values.

Server error - Something went wrong on the Cloud Elements server
*/
type DeleteInstancesTransformationByObjectNameInternalServerError struct {
}

func (o *DeleteInstancesTransformationByObjectNameInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /instances/transformations/{objectName}][%d] deleteInstancesTransformationByObjectNameInternalServerError ", 500)
}

func (o *DeleteInstancesTransformationByObjectNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
