// Code generated by go-swagger; DO NOT EDIT.

package instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteInstancesTransformationByObjectName2Reader is a Reader for the DeleteInstancesTransformationByObjectName2 structure.
type DeleteInstancesTransformationByObjectName2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteInstancesTransformationByObjectName2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteInstancesTransformationByObjectName2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteInstancesTransformationByObjectName2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDeleteInstancesTransformationByObjectName2Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteInstancesTransformationByObjectName2Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteInstancesTransformationByObjectName2NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewDeleteInstancesTransformationByObjectName2MethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 406:
		result := NewDeleteInstancesTransformationByObjectName2NotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewDeleteInstancesTransformationByObjectName2Conflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 415:
		result := NewDeleteInstancesTransformationByObjectName2UnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteInstancesTransformationByObjectName2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteInstancesTransformationByObjectName2OK creates a DeleteInstancesTransformationByObjectName2OK with default headers values
func NewDeleteInstancesTransformationByObjectName2OK() *DeleteInstancesTransformationByObjectName2OK {
	return &DeleteInstancesTransformationByObjectName2OK{}
}

/*DeleteInstancesTransformationByObjectName2OK handles this case with default header values.

OK - Everything worked as expected
*/
type DeleteInstancesTransformationByObjectName2OK struct {
}

func (o *DeleteInstancesTransformationByObjectName2OK) Error() string {
	return fmt.Sprintf("[DELETE /instances/{id}/transformations/{objectName}][%d] deleteInstancesTransformationByObjectName2OK ", 200)
}

func (o *DeleteInstancesTransformationByObjectName2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInstancesTransformationByObjectName2BadRequest creates a DeleteInstancesTransformationByObjectName2BadRequest with default headers values
func NewDeleteInstancesTransformationByObjectName2BadRequest() *DeleteInstancesTransformationByObjectName2BadRequest {
	return &DeleteInstancesTransformationByObjectName2BadRequest{}
}

/*DeleteInstancesTransformationByObjectName2BadRequest handles this case with default header values.

Bad Request - Often due to a missing request parameter
*/
type DeleteInstancesTransformationByObjectName2BadRequest struct {
}

func (o *DeleteInstancesTransformationByObjectName2BadRequest) Error() string {
	return fmt.Sprintf("[DELETE /instances/{id}/transformations/{objectName}][%d] deleteInstancesTransformationByObjectName2BadRequest ", 400)
}

func (o *DeleteInstancesTransformationByObjectName2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInstancesTransformationByObjectName2Unauthorized creates a DeleteInstancesTransformationByObjectName2Unauthorized with default headers values
func NewDeleteInstancesTransformationByObjectName2Unauthorized() *DeleteInstancesTransformationByObjectName2Unauthorized {
	return &DeleteInstancesTransformationByObjectName2Unauthorized{}
}

/*DeleteInstancesTransformationByObjectName2Unauthorized handles this case with default header values.

Unauthorized - An invalid element token, user secret and/or org secret provided
*/
type DeleteInstancesTransformationByObjectName2Unauthorized struct {
}

func (o *DeleteInstancesTransformationByObjectName2Unauthorized) Error() string {
	return fmt.Sprintf("[DELETE /instances/{id}/transformations/{objectName}][%d] deleteInstancesTransformationByObjectName2Unauthorized ", 401)
}

func (o *DeleteInstancesTransformationByObjectName2Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInstancesTransformationByObjectName2Forbidden creates a DeleteInstancesTransformationByObjectName2Forbidden with default headers values
func NewDeleteInstancesTransformationByObjectName2Forbidden() *DeleteInstancesTransformationByObjectName2Forbidden {
	return &DeleteInstancesTransformationByObjectName2Forbidden{}
}

/*DeleteInstancesTransformationByObjectName2Forbidden handles this case with default header values.

Forbidden - Access to the resource by the provider is forbidden
*/
type DeleteInstancesTransformationByObjectName2Forbidden struct {
}

func (o *DeleteInstancesTransformationByObjectName2Forbidden) Error() string {
	return fmt.Sprintf("[DELETE /instances/{id}/transformations/{objectName}][%d] deleteInstancesTransformationByObjectName2Forbidden ", 403)
}

func (o *DeleteInstancesTransformationByObjectName2Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInstancesTransformationByObjectName2NotFound creates a DeleteInstancesTransformationByObjectName2NotFound with default headers values
func NewDeleteInstancesTransformationByObjectName2NotFound() *DeleteInstancesTransformationByObjectName2NotFound {
	return &DeleteInstancesTransformationByObjectName2NotFound{}
}

/*DeleteInstancesTransformationByObjectName2NotFound handles this case with default header values.

Not found - The requested resource is not found
*/
type DeleteInstancesTransformationByObjectName2NotFound struct {
}

func (o *DeleteInstancesTransformationByObjectName2NotFound) Error() string {
	return fmt.Sprintf("[DELETE /instances/{id}/transformations/{objectName}][%d] deleteInstancesTransformationByObjectName2NotFound ", 404)
}

func (o *DeleteInstancesTransformationByObjectName2NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInstancesTransformationByObjectName2MethodNotAllowed creates a DeleteInstancesTransformationByObjectName2MethodNotAllowed with default headers values
func NewDeleteInstancesTransformationByObjectName2MethodNotAllowed() *DeleteInstancesTransformationByObjectName2MethodNotAllowed {
	return &DeleteInstancesTransformationByObjectName2MethodNotAllowed{}
}

/*DeleteInstancesTransformationByObjectName2MethodNotAllowed handles this case with default header values.

Method not allowed - Incorrect HTTP verb used, e.g., GET used when POST expected
*/
type DeleteInstancesTransformationByObjectName2MethodNotAllowed struct {
}

func (o *DeleteInstancesTransformationByObjectName2MethodNotAllowed) Error() string {
	return fmt.Sprintf("[DELETE /instances/{id}/transformations/{objectName}][%d] deleteInstancesTransformationByObjectName2MethodNotAllowed ", 405)
}

func (o *DeleteInstancesTransformationByObjectName2MethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInstancesTransformationByObjectName2NotAcceptable creates a DeleteInstancesTransformationByObjectName2NotAcceptable with default headers values
func NewDeleteInstancesTransformationByObjectName2NotAcceptable() *DeleteInstancesTransformationByObjectName2NotAcceptable {
	return &DeleteInstancesTransformationByObjectName2NotAcceptable{}
}

/*DeleteInstancesTransformationByObjectName2NotAcceptable handles this case with default header values.

Not acceptable - The response content type does not match the 'Accept' header value
*/
type DeleteInstancesTransformationByObjectName2NotAcceptable struct {
}

func (o *DeleteInstancesTransformationByObjectName2NotAcceptable) Error() string {
	return fmt.Sprintf("[DELETE /instances/{id}/transformations/{objectName}][%d] deleteInstancesTransformationByObjectName2NotAcceptable ", 406)
}

func (o *DeleteInstancesTransformationByObjectName2NotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInstancesTransformationByObjectName2Conflict creates a DeleteInstancesTransformationByObjectName2Conflict with default headers values
func NewDeleteInstancesTransformationByObjectName2Conflict() *DeleteInstancesTransformationByObjectName2Conflict {
	return &DeleteInstancesTransformationByObjectName2Conflict{}
}

/*DeleteInstancesTransformationByObjectName2Conflict handles this case with default header values.

Conflict - If a resource being created already exists
*/
type DeleteInstancesTransformationByObjectName2Conflict struct {
}

func (o *DeleteInstancesTransformationByObjectName2Conflict) Error() string {
	return fmt.Sprintf("[DELETE /instances/{id}/transformations/{objectName}][%d] deleteInstancesTransformationByObjectName2Conflict ", 409)
}

func (o *DeleteInstancesTransformationByObjectName2Conflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInstancesTransformationByObjectName2UnsupportedMediaType creates a DeleteInstancesTransformationByObjectName2UnsupportedMediaType with default headers values
func NewDeleteInstancesTransformationByObjectName2UnsupportedMediaType() *DeleteInstancesTransformationByObjectName2UnsupportedMediaType {
	return &DeleteInstancesTransformationByObjectName2UnsupportedMediaType{}
}

/*DeleteInstancesTransformationByObjectName2UnsupportedMediaType handles this case with default header values.

Unsupported media type - The server cannot handle the requested Content-Type
*/
type DeleteInstancesTransformationByObjectName2UnsupportedMediaType struct {
}

func (o *DeleteInstancesTransformationByObjectName2UnsupportedMediaType) Error() string {
	return fmt.Sprintf("[DELETE /instances/{id}/transformations/{objectName}][%d] deleteInstancesTransformationByObjectName2UnsupportedMediaType ", 415)
}

func (o *DeleteInstancesTransformationByObjectName2UnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInstancesTransformationByObjectName2InternalServerError creates a DeleteInstancesTransformationByObjectName2InternalServerError with default headers values
func NewDeleteInstancesTransformationByObjectName2InternalServerError() *DeleteInstancesTransformationByObjectName2InternalServerError {
	return &DeleteInstancesTransformationByObjectName2InternalServerError{}
}

/*DeleteInstancesTransformationByObjectName2InternalServerError handles this case with default header values.

Server error - Something went wrong on the Cloud Elements server
*/
type DeleteInstancesTransformationByObjectName2InternalServerError struct {
}

func (o *DeleteInstancesTransformationByObjectName2InternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /instances/{id}/transformations/{objectName}][%d] deleteInstancesTransformationByObjectName2InternalServerError ", 500)
}

func (o *DeleteInstancesTransformationByObjectName2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
