// Code generated by go-swagger; DO NOT EDIT.

package instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/akrausesap/goexperiments/openconnectors/util/connectorclient/models"
)

// GetInstancesTransformationByObjectNameReader is a Reader for the GetInstancesTransformationByObjectName structure.
type GetInstancesTransformationByObjectNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInstancesTransformationByObjectNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetInstancesTransformationByObjectNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetInstancesTransformationByObjectNameBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetInstancesTransformationByObjectNameUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetInstancesTransformationByObjectNameForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetInstancesTransformationByObjectNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewGetInstancesTransformationByObjectNameMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 406:
		result := NewGetInstancesTransformationByObjectNameNotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewGetInstancesTransformationByObjectNameConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 415:
		result := NewGetInstancesTransformationByObjectNameUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetInstancesTransformationByObjectNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetInstancesTransformationByObjectNameOK creates a GetInstancesTransformationByObjectNameOK with default headers values
func NewGetInstancesTransformationByObjectNameOK() *GetInstancesTransformationByObjectNameOK {
	return &GetInstancesTransformationByObjectNameOK{}
}

/*GetInstancesTransformationByObjectNameOK handles this case with default header values.

OK - Everything worked as expected
*/
type GetInstancesTransformationByObjectNameOK struct {
	Payload *models.Transformation
}

func (o *GetInstancesTransformationByObjectNameOK) Error() string {
	return fmt.Sprintf("[GET /instances/transformations/{objectName}][%d] getInstancesTransformationByObjectNameOK  %+v", 200, o.Payload)
}

func (o *GetInstancesTransformationByObjectNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Transformation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInstancesTransformationByObjectNameBadRequest creates a GetInstancesTransformationByObjectNameBadRequest with default headers values
func NewGetInstancesTransformationByObjectNameBadRequest() *GetInstancesTransformationByObjectNameBadRequest {
	return &GetInstancesTransformationByObjectNameBadRequest{}
}

/*GetInstancesTransformationByObjectNameBadRequest handles this case with default header values.

Bad Request - Often due to a missing request parameter
*/
type GetInstancesTransformationByObjectNameBadRequest struct {
}

func (o *GetInstancesTransformationByObjectNameBadRequest) Error() string {
	return fmt.Sprintf("[GET /instances/transformations/{objectName}][%d] getInstancesTransformationByObjectNameBadRequest ", 400)
}

func (o *GetInstancesTransformationByObjectNameBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesTransformationByObjectNameUnauthorized creates a GetInstancesTransformationByObjectNameUnauthorized with default headers values
func NewGetInstancesTransformationByObjectNameUnauthorized() *GetInstancesTransformationByObjectNameUnauthorized {
	return &GetInstancesTransformationByObjectNameUnauthorized{}
}

/*GetInstancesTransformationByObjectNameUnauthorized handles this case with default header values.

Unauthorized - An invalid element token, user secret and/or org secret provided
*/
type GetInstancesTransformationByObjectNameUnauthorized struct {
}

func (o *GetInstancesTransformationByObjectNameUnauthorized) Error() string {
	return fmt.Sprintf("[GET /instances/transformations/{objectName}][%d] getInstancesTransformationByObjectNameUnauthorized ", 401)
}

func (o *GetInstancesTransformationByObjectNameUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesTransformationByObjectNameForbidden creates a GetInstancesTransformationByObjectNameForbidden with default headers values
func NewGetInstancesTransformationByObjectNameForbidden() *GetInstancesTransformationByObjectNameForbidden {
	return &GetInstancesTransformationByObjectNameForbidden{}
}

/*GetInstancesTransformationByObjectNameForbidden handles this case with default header values.

Forbidden - Access to the resource by the provider is forbidden
*/
type GetInstancesTransformationByObjectNameForbidden struct {
}

func (o *GetInstancesTransformationByObjectNameForbidden) Error() string {
	return fmt.Sprintf("[GET /instances/transformations/{objectName}][%d] getInstancesTransformationByObjectNameForbidden ", 403)
}

func (o *GetInstancesTransformationByObjectNameForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesTransformationByObjectNameNotFound creates a GetInstancesTransformationByObjectNameNotFound with default headers values
func NewGetInstancesTransformationByObjectNameNotFound() *GetInstancesTransformationByObjectNameNotFound {
	return &GetInstancesTransformationByObjectNameNotFound{}
}

/*GetInstancesTransformationByObjectNameNotFound handles this case with default header values.

Not found - The requested resource is not found
*/
type GetInstancesTransformationByObjectNameNotFound struct {
}

func (o *GetInstancesTransformationByObjectNameNotFound) Error() string {
	return fmt.Sprintf("[GET /instances/transformations/{objectName}][%d] getInstancesTransformationByObjectNameNotFound ", 404)
}

func (o *GetInstancesTransformationByObjectNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesTransformationByObjectNameMethodNotAllowed creates a GetInstancesTransformationByObjectNameMethodNotAllowed with default headers values
func NewGetInstancesTransformationByObjectNameMethodNotAllowed() *GetInstancesTransformationByObjectNameMethodNotAllowed {
	return &GetInstancesTransformationByObjectNameMethodNotAllowed{}
}

/*GetInstancesTransformationByObjectNameMethodNotAllowed handles this case with default header values.

Method not allowed - Incorrect HTTP verb used, e.g., GET used when POST expected
*/
type GetInstancesTransformationByObjectNameMethodNotAllowed struct {
}

func (o *GetInstancesTransformationByObjectNameMethodNotAllowed) Error() string {
	return fmt.Sprintf("[GET /instances/transformations/{objectName}][%d] getInstancesTransformationByObjectNameMethodNotAllowed ", 405)
}

func (o *GetInstancesTransformationByObjectNameMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesTransformationByObjectNameNotAcceptable creates a GetInstancesTransformationByObjectNameNotAcceptable with default headers values
func NewGetInstancesTransformationByObjectNameNotAcceptable() *GetInstancesTransformationByObjectNameNotAcceptable {
	return &GetInstancesTransformationByObjectNameNotAcceptable{}
}

/*GetInstancesTransformationByObjectNameNotAcceptable handles this case with default header values.

Not acceptable - The response content type does not match the 'Accept' header value
*/
type GetInstancesTransformationByObjectNameNotAcceptable struct {
}

func (o *GetInstancesTransformationByObjectNameNotAcceptable) Error() string {
	return fmt.Sprintf("[GET /instances/transformations/{objectName}][%d] getInstancesTransformationByObjectNameNotAcceptable ", 406)
}

func (o *GetInstancesTransformationByObjectNameNotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesTransformationByObjectNameConflict creates a GetInstancesTransformationByObjectNameConflict with default headers values
func NewGetInstancesTransformationByObjectNameConflict() *GetInstancesTransformationByObjectNameConflict {
	return &GetInstancesTransformationByObjectNameConflict{}
}

/*GetInstancesTransformationByObjectNameConflict handles this case with default header values.

Conflict - If a resource being created already exists
*/
type GetInstancesTransformationByObjectNameConflict struct {
}

func (o *GetInstancesTransformationByObjectNameConflict) Error() string {
	return fmt.Sprintf("[GET /instances/transformations/{objectName}][%d] getInstancesTransformationByObjectNameConflict ", 409)
}

func (o *GetInstancesTransformationByObjectNameConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesTransformationByObjectNameUnsupportedMediaType creates a GetInstancesTransformationByObjectNameUnsupportedMediaType with default headers values
func NewGetInstancesTransformationByObjectNameUnsupportedMediaType() *GetInstancesTransformationByObjectNameUnsupportedMediaType {
	return &GetInstancesTransformationByObjectNameUnsupportedMediaType{}
}

/*GetInstancesTransformationByObjectNameUnsupportedMediaType handles this case with default header values.

Unsupported media type - The server cannot handle the requested Content-Type
*/
type GetInstancesTransformationByObjectNameUnsupportedMediaType struct {
}

func (o *GetInstancesTransformationByObjectNameUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[GET /instances/transformations/{objectName}][%d] getInstancesTransformationByObjectNameUnsupportedMediaType ", 415)
}

func (o *GetInstancesTransformationByObjectNameUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesTransformationByObjectNameInternalServerError creates a GetInstancesTransformationByObjectNameInternalServerError with default headers values
func NewGetInstancesTransformationByObjectNameInternalServerError() *GetInstancesTransformationByObjectNameInternalServerError {
	return &GetInstancesTransformationByObjectNameInternalServerError{}
}

/*GetInstancesTransformationByObjectNameInternalServerError handles this case with default header values.

Server error - Something went wrong on the Cloud Elements server
*/
type GetInstancesTransformationByObjectNameInternalServerError struct {
}

func (o *GetInstancesTransformationByObjectNameInternalServerError) Error() string {
	return fmt.Sprintf("[GET /instances/transformations/{objectName}][%d] getInstancesTransformationByObjectNameInternalServerError ", 500)
}

func (o *GetInstancesTransformationByObjectNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
