// Code generated by go-swagger; DO NOT EDIT.

package instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetInstancesObjectsObjectNameDefinitions2Params creates a new GetInstancesObjectsObjectNameDefinitions2Params object
// with the default values initialized.
func NewGetInstancesObjectsObjectNameDefinitions2Params() *GetInstancesObjectsObjectNameDefinitions2Params {
	var ()
	return &GetInstancesObjectsObjectNameDefinitions2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetInstancesObjectsObjectNameDefinitions2ParamsWithTimeout creates a new GetInstancesObjectsObjectNameDefinitions2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetInstancesObjectsObjectNameDefinitions2ParamsWithTimeout(timeout time.Duration) *GetInstancesObjectsObjectNameDefinitions2Params {
	var ()
	return &GetInstancesObjectsObjectNameDefinitions2Params{

		timeout: timeout,
	}
}

// NewGetInstancesObjectsObjectNameDefinitions2ParamsWithContext creates a new GetInstancesObjectsObjectNameDefinitions2Params object
// with the default values initialized, and the ability to set a context for a request
func NewGetInstancesObjectsObjectNameDefinitions2ParamsWithContext(ctx context.Context) *GetInstancesObjectsObjectNameDefinitions2Params {
	var ()
	return &GetInstancesObjectsObjectNameDefinitions2Params{

		Context: ctx,
	}
}

// NewGetInstancesObjectsObjectNameDefinitions2ParamsWithHTTPClient creates a new GetInstancesObjectsObjectNameDefinitions2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetInstancesObjectsObjectNameDefinitions2ParamsWithHTTPClient(client *http.Client) *GetInstancesObjectsObjectNameDefinitions2Params {
	var ()
	return &GetInstancesObjectsObjectNameDefinitions2Params{
		HTTPClient: client,
	}
}

/*GetInstancesObjectsObjectNameDefinitions2Params contains all the parameters to send to the API endpoint
for the get instances objects object name definitions2 operation typically these are written to a http.Request
*/
type GetInstancesObjectsObjectNameDefinitions2Params struct {

	/*Authorization
	  The authorization tokens. The format for the header value is 'User &lt;user secret&gt;, Organization &lt;org secret&gt;'

	*/
	Authorization string
	/*ID
	  The ID of the instance

	*/
	ID int64
	/*ObjectName
	  The name of the object

	*/
	ObjectName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get instances objects object name definitions2 params
func (o *GetInstancesObjectsObjectNameDefinitions2Params) WithTimeout(timeout time.Duration) *GetInstancesObjectsObjectNameDefinitions2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get instances objects object name definitions2 params
func (o *GetInstancesObjectsObjectNameDefinitions2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get instances objects object name definitions2 params
func (o *GetInstancesObjectsObjectNameDefinitions2Params) WithContext(ctx context.Context) *GetInstancesObjectsObjectNameDefinitions2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get instances objects object name definitions2 params
func (o *GetInstancesObjectsObjectNameDefinitions2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get instances objects object name definitions2 params
func (o *GetInstancesObjectsObjectNameDefinitions2Params) WithHTTPClient(client *http.Client) *GetInstancesObjectsObjectNameDefinitions2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get instances objects object name definitions2 params
func (o *GetInstancesObjectsObjectNameDefinitions2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get instances objects object name definitions2 params
func (o *GetInstancesObjectsObjectNameDefinitions2Params) WithAuthorization(authorization string) *GetInstancesObjectsObjectNameDefinitions2Params {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get instances objects object name definitions2 params
func (o *GetInstancesObjectsObjectNameDefinitions2Params) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithID adds the id to the get instances objects object name definitions2 params
func (o *GetInstancesObjectsObjectNameDefinitions2Params) WithID(id int64) *GetInstancesObjectsObjectNameDefinitions2Params {
	o.SetID(id)
	return o
}

// SetID adds the id to the get instances objects object name definitions2 params
func (o *GetInstancesObjectsObjectNameDefinitions2Params) SetID(id int64) {
	o.ID = id
}

// WithObjectName adds the objectName to the get instances objects object name definitions2 params
func (o *GetInstancesObjectsObjectNameDefinitions2Params) WithObjectName(objectName string) *GetInstancesObjectsObjectNameDefinitions2Params {
	o.SetObjectName(objectName)
	return o
}

// SetObjectName adds the objectName to the get instances objects object name definitions2 params
func (o *GetInstancesObjectsObjectNameDefinitions2Params) SetObjectName(objectName string) {
	o.ObjectName = objectName
}

// WriteToRequest writes these params to a swagger request
func (o *GetInstancesObjectsObjectNameDefinitions2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// path param objectName
	if err := r.SetPathParam("objectName", o.ObjectName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
