// Code generated by go-swagger; DO NOT EDIT.

package instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetInstancesEvents2Params creates a new GetInstancesEvents2Params object
// with the default values initialized.
func NewGetInstancesEvents2Params() *GetInstancesEvents2Params {
	var ()
	return &GetInstancesEvents2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetInstancesEvents2ParamsWithTimeout creates a new GetInstancesEvents2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetInstancesEvents2ParamsWithTimeout(timeout time.Duration) *GetInstancesEvents2Params {
	var ()
	return &GetInstancesEvents2Params{

		timeout: timeout,
	}
}

// NewGetInstancesEvents2ParamsWithContext creates a new GetInstancesEvents2Params object
// with the default values initialized, and the ability to set a context for a request
func NewGetInstancesEvents2ParamsWithContext(ctx context.Context) *GetInstancesEvents2Params {
	var ()
	return &GetInstancesEvents2Params{

		Context: ctx,
	}
}

// NewGetInstancesEvents2ParamsWithHTTPClient creates a new GetInstancesEvents2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetInstancesEvents2ParamsWithHTTPClient(client *http.Client) *GetInstancesEvents2Params {
	var ()
	return &GetInstancesEvents2Params{
		HTTPClient: client,
	}
}

/*GetInstancesEvents2Params contains all the parameters to send to the API endpoint
for the get instances events2 operation typically these are written to a http.Request
*/
type GetInstancesEvents2Params struct {

	/*Authorization
	  The authorization tokens. The format for the header value is 'User &lt;user secret&gt;, Organization &lt;org secret&gt;'

	*/
	Authorization string
	/*ID
	  The ID of the element instance

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get instances events2 params
func (o *GetInstancesEvents2Params) WithTimeout(timeout time.Duration) *GetInstancesEvents2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get instances events2 params
func (o *GetInstancesEvents2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get instances events2 params
func (o *GetInstancesEvents2Params) WithContext(ctx context.Context) *GetInstancesEvents2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get instances events2 params
func (o *GetInstancesEvents2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get instances events2 params
func (o *GetInstancesEvents2Params) WithHTTPClient(client *http.Client) *GetInstancesEvents2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get instances events2 params
func (o *GetInstancesEvents2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get instances events2 params
func (o *GetInstancesEvents2Params) WithAuthorization(authorization string) *GetInstancesEvents2Params {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get instances events2 params
func (o *GetInstancesEvents2Params) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithID adds the id to the get instances events2 params
func (o *GetInstancesEvents2Params) WithID(id int64) *GetInstancesEvents2Params {
	o.SetID(id)
	return o
}

// SetID adds the id to the get instances events2 params
func (o *GetInstancesEvents2Params) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetInstancesEvents2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
