// Code generated by go-swagger; DO NOT EDIT.

package instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/akrausesap/goexperiments/openconnectors/util/connectorclient/models"
)

// GetInstancesConfigurationByConfigId2Reader is a Reader for the GetInstancesConfigurationByConfigId2 structure.
type GetInstancesConfigurationByConfigId2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInstancesConfigurationByConfigId2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetInstancesConfigurationByConfigId2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetInstancesConfigurationByConfigId2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetInstancesConfigurationByConfigId2Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetInstancesConfigurationByConfigId2Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetInstancesConfigurationByConfigId2NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewGetInstancesConfigurationByConfigId2MethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 406:
		result := NewGetInstancesConfigurationByConfigId2NotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewGetInstancesConfigurationByConfigId2Conflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 415:
		result := NewGetInstancesConfigurationByConfigId2UnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetInstancesConfigurationByConfigId2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetInstancesConfigurationByConfigId2OK creates a GetInstancesConfigurationByConfigId2OK with default headers values
func NewGetInstancesConfigurationByConfigId2OK() *GetInstancesConfigurationByConfigId2OK {
	return &GetInstancesConfigurationByConfigId2OK{}
}

/*GetInstancesConfigurationByConfigId2OK handles this case with default header values.

OK - Everything worked as expected
*/
type GetInstancesConfigurationByConfigId2OK struct {
	Payload *models.ElementInstanceConfig
}

func (o *GetInstancesConfigurationByConfigId2OK) Error() string {
	return fmt.Sprintf("[GET /instances/{id}/configuration/{configId}][%d] getInstancesConfigurationByConfigId2OK  %+v", 200, o.Payload)
}

func (o *GetInstancesConfigurationByConfigId2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ElementInstanceConfig)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInstancesConfigurationByConfigId2BadRequest creates a GetInstancesConfigurationByConfigId2BadRequest with default headers values
func NewGetInstancesConfigurationByConfigId2BadRequest() *GetInstancesConfigurationByConfigId2BadRequest {
	return &GetInstancesConfigurationByConfigId2BadRequest{}
}

/*GetInstancesConfigurationByConfigId2BadRequest handles this case with default header values.

Bad Request - Often due to a missing request parameter
*/
type GetInstancesConfigurationByConfigId2BadRequest struct {
}

func (o *GetInstancesConfigurationByConfigId2BadRequest) Error() string {
	return fmt.Sprintf("[GET /instances/{id}/configuration/{configId}][%d] getInstancesConfigurationByConfigId2BadRequest ", 400)
}

func (o *GetInstancesConfigurationByConfigId2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesConfigurationByConfigId2Unauthorized creates a GetInstancesConfigurationByConfigId2Unauthorized with default headers values
func NewGetInstancesConfigurationByConfigId2Unauthorized() *GetInstancesConfigurationByConfigId2Unauthorized {
	return &GetInstancesConfigurationByConfigId2Unauthorized{}
}

/*GetInstancesConfigurationByConfigId2Unauthorized handles this case with default header values.

Unauthorized - An invalid element token, user secret and/or org secret provided
*/
type GetInstancesConfigurationByConfigId2Unauthorized struct {
}

func (o *GetInstancesConfigurationByConfigId2Unauthorized) Error() string {
	return fmt.Sprintf("[GET /instances/{id}/configuration/{configId}][%d] getInstancesConfigurationByConfigId2Unauthorized ", 401)
}

func (o *GetInstancesConfigurationByConfigId2Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesConfigurationByConfigId2Forbidden creates a GetInstancesConfigurationByConfigId2Forbidden with default headers values
func NewGetInstancesConfigurationByConfigId2Forbidden() *GetInstancesConfigurationByConfigId2Forbidden {
	return &GetInstancesConfigurationByConfigId2Forbidden{}
}

/*GetInstancesConfigurationByConfigId2Forbidden handles this case with default header values.

Forbidden - Access to the resource by the provider is forbidden
*/
type GetInstancesConfigurationByConfigId2Forbidden struct {
}

func (o *GetInstancesConfigurationByConfigId2Forbidden) Error() string {
	return fmt.Sprintf("[GET /instances/{id}/configuration/{configId}][%d] getInstancesConfigurationByConfigId2Forbidden ", 403)
}

func (o *GetInstancesConfigurationByConfigId2Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesConfigurationByConfigId2NotFound creates a GetInstancesConfigurationByConfigId2NotFound with default headers values
func NewGetInstancesConfigurationByConfigId2NotFound() *GetInstancesConfigurationByConfigId2NotFound {
	return &GetInstancesConfigurationByConfigId2NotFound{}
}

/*GetInstancesConfigurationByConfigId2NotFound handles this case with default header values.

Not found - The requested resource is not found
*/
type GetInstancesConfigurationByConfigId2NotFound struct {
}

func (o *GetInstancesConfigurationByConfigId2NotFound) Error() string {
	return fmt.Sprintf("[GET /instances/{id}/configuration/{configId}][%d] getInstancesConfigurationByConfigId2NotFound ", 404)
}

func (o *GetInstancesConfigurationByConfigId2NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesConfigurationByConfigId2MethodNotAllowed creates a GetInstancesConfigurationByConfigId2MethodNotAllowed with default headers values
func NewGetInstancesConfigurationByConfigId2MethodNotAllowed() *GetInstancesConfigurationByConfigId2MethodNotAllowed {
	return &GetInstancesConfigurationByConfigId2MethodNotAllowed{}
}

/*GetInstancesConfigurationByConfigId2MethodNotAllowed handles this case with default header values.

Method not allowed - Incorrect HTTP verb used, e.g., GET used when POST expected
*/
type GetInstancesConfigurationByConfigId2MethodNotAllowed struct {
}

func (o *GetInstancesConfigurationByConfigId2MethodNotAllowed) Error() string {
	return fmt.Sprintf("[GET /instances/{id}/configuration/{configId}][%d] getInstancesConfigurationByConfigId2MethodNotAllowed ", 405)
}

func (o *GetInstancesConfigurationByConfigId2MethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesConfigurationByConfigId2NotAcceptable creates a GetInstancesConfigurationByConfigId2NotAcceptable with default headers values
func NewGetInstancesConfigurationByConfigId2NotAcceptable() *GetInstancesConfigurationByConfigId2NotAcceptable {
	return &GetInstancesConfigurationByConfigId2NotAcceptable{}
}

/*GetInstancesConfigurationByConfigId2NotAcceptable handles this case with default header values.

Not acceptable - The response content type does not match the 'Accept' header value
*/
type GetInstancesConfigurationByConfigId2NotAcceptable struct {
}

func (o *GetInstancesConfigurationByConfigId2NotAcceptable) Error() string {
	return fmt.Sprintf("[GET /instances/{id}/configuration/{configId}][%d] getInstancesConfigurationByConfigId2NotAcceptable ", 406)
}

func (o *GetInstancesConfigurationByConfigId2NotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesConfigurationByConfigId2Conflict creates a GetInstancesConfigurationByConfigId2Conflict with default headers values
func NewGetInstancesConfigurationByConfigId2Conflict() *GetInstancesConfigurationByConfigId2Conflict {
	return &GetInstancesConfigurationByConfigId2Conflict{}
}

/*GetInstancesConfigurationByConfigId2Conflict handles this case with default header values.

Conflict - If a resource being created already exists
*/
type GetInstancesConfigurationByConfigId2Conflict struct {
}

func (o *GetInstancesConfigurationByConfigId2Conflict) Error() string {
	return fmt.Sprintf("[GET /instances/{id}/configuration/{configId}][%d] getInstancesConfigurationByConfigId2Conflict ", 409)
}

func (o *GetInstancesConfigurationByConfigId2Conflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesConfigurationByConfigId2UnsupportedMediaType creates a GetInstancesConfigurationByConfigId2UnsupportedMediaType with default headers values
func NewGetInstancesConfigurationByConfigId2UnsupportedMediaType() *GetInstancesConfigurationByConfigId2UnsupportedMediaType {
	return &GetInstancesConfigurationByConfigId2UnsupportedMediaType{}
}

/*GetInstancesConfigurationByConfigId2UnsupportedMediaType handles this case with default header values.

Unsupported media type - The server cannot handle the requested Content-Type
*/
type GetInstancesConfigurationByConfigId2UnsupportedMediaType struct {
}

func (o *GetInstancesConfigurationByConfigId2UnsupportedMediaType) Error() string {
	return fmt.Sprintf("[GET /instances/{id}/configuration/{configId}][%d] getInstancesConfigurationByConfigId2UnsupportedMediaType ", 415)
}

func (o *GetInstancesConfigurationByConfigId2UnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesConfigurationByConfigId2InternalServerError creates a GetInstancesConfigurationByConfigId2InternalServerError with default headers values
func NewGetInstancesConfigurationByConfigId2InternalServerError() *GetInstancesConfigurationByConfigId2InternalServerError {
	return &GetInstancesConfigurationByConfigId2InternalServerError{}
}

/*GetInstancesConfigurationByConfigId2InternalServerError handles this case with default header values.

Server error - Something went wrong on the Cloud Elements server
*/
type GetInstancesConfigurationByConfigId2InternalServerError struct {
}

func (o *GetInstancesConfigurationByConfigId2InternalServerError) Error() string {
	return fmt.Sprintf("[GET /instances/{id}/configuration/{configId}][%d] getInstancesConfigurationByConfigId2InternalServerError ", 500)
}

func (o *GetInstancesConfigurationByConfigId2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
