// Code generated by go-swagger; DO NOT EDIT.

package instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetInstancesEventByEventIDParams creates a new GetInstancesEventByEventIDParams object
// with the default values initialized.
func NewGetInstancesEventByEventIDParams() *GetInstancesEventByEventIDParams {
	var ()
	return &GetInstancesEventByEventIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetInstancesEventByEventIDParamsWithTimeout creates a new GetInstancesEventByEventIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetInstancesEventByEventIDParamsWithTimeout(timeout time.Duration) *GetInstancesEventByEventIDParams {
	var ()
	return &GetInstancesEventByEventIDParams{

		timeout: timeout,
	}
}

// NewGetInstancesEventByEventIDParamsWithContext creates a new GetInstancesEventByEventIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetInstancesEventByEventIDParamsWithContext(ctx context.Context) *GetInstancesEventByEventIDParams {
	var ()
	return &GetInstancesEventByEventIDParams{

		Context: ctx,
	}
}

// NewGetInstancesEventByEventIDParamsWithHTTPClient creates a new GetInstancesEventByEventIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetInstancesEventByEventIDParamsWithHTTPClient(client *http.Client) *GetInstancesEventByEventIDParams {
	var ()
	return &GetInstancesEventByEventIDParams{
		HTTPClient: client,
	}
}

/*GetInstancesEventByEventIDParams contains all the parameters to send to the API endpoint
for the get instances event by event Id operation typically these are written to a http.Request
*/
type GetInstancesEventByEventIDParams struct {

	/*Authorization
	  The authorization tokens. The format for the header value is 'User &lt;user secret&gt;, Organization &lt;org secret&gt;'

	*/
	Authorization string
	/*EventID
	  The ID of the event

	*/
	EventID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get instances event by event Id params
func (o *GetInstancesEventByEventIDParams) WithTimeout(timeout time.Duration) *GetInstancesEventByEventIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get instances event by event Id params
func (o *GetInstancesEventByEventIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get instances event by event Id params
func (o *GetInstancesEventByEventIDParams) WithContext(ctx context.Context) *GetInstancesEventByEventIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get instances event by event Id params
func (o *GetInstancesEventByEventIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get instances event by event Id params
func (o *GetInstancesEventByEventIDParams) WithHTTPClient(client *http.Client) *GetInstancesEventByEventIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get instances event by event Id params
func (o *GetInstancesEventByEventIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get instances event by event Id params
func (o *GetInstancesEventByEventIDParams) WithAuthorization(authorization string) *GetInstancesEventByEventIDParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get instances event by event Id params
func (o *GetInstancesEventByEventIDParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithEventID adds the eventID to the get instances event by event Id params
func (o *GetInstancesEventByEventIDParams) WithEventID(eventID int64) *GetInstancesEventByEventIDParams {
	o.SetEventID(eventID)
	return o
}

// SetEventID adds the eventId to the get instances event by event Id params
func (o *GetInstancesEventByEventIDParams) SetEventID(eventID int64) {
	o.EventID = eventID
}

// WriteToRequest writes these params to a swagger request
func (o *GetInstancesEventByEventIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param eventId
	if err := r.SetPathParam("eventId", swag.FormatInt64(o.EventID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
