// Code generated by go-swagger; DO NOT EDIT.

package instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetInstancesDocsReader is a Reader for the GetInstancesDocs structure.
type GetInstancesDocsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInstancesDocsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetInstancesDocsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetInstancesDocsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetInstancesDocsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetInstancesDocsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetInstancesDocsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewGetInstancesDocsMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 406:
		result := NewGetInstancesDocsNotAcceptable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewGetInstancesDocsConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 415:
		result := NewGetInstancesDocsUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetInstancesDocsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetInstancesDocsOK creates a GetInstancesDocsOK with default headers values
func NewGetInstancesDocsOK() *GetInstancesDocsOK {
	return &GetInstancesDocsOK{}
}

/*GetInstancesDocsOK handles this case with default header values.

OK - Everything worked as expected
*/
type GetInstancesDocsOK struct {
	Payload interface{}
}

func (o *GetInstancesDocsOK) Error() string {
	return fmt.Sprintf("[GET /instances/docs][%d] getInstancesDocsOK  %+v", 200, o.Payload)
}

func (o *GetInstancesDocsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInstancesDocsBadRequest creates a GetInstancesDocsBadRequest with default headers values
func NewGetInstancesDocsBadRequest() *GetInstancesDocsBadRequest {
	return &GetInstancesDocsBadRequest{}
}

/*GetInstancesDocsBadRequest handles this case with default header values.

Bad Request - Often due to a missing request parameter
*/
type GetInstancesDocsBadRequest struct {
}

func (o *GetInstancesDocsBadRequest) Error() string {
	return fmt.Sprintf("[GET /instances/docs][%d] getInstancesDocsBadRequest ", 400)
}

func (o *GetInstancesDocsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesDocsUnauthorized creates a GetInstancesDocsUnauthorized with default headers values
func NewGetInstancesDocsUnauthorized() *GetInstancesDocsUnauthorized {
	return &GetInstancesDocsUnauthorized{}
}

/*GetInstancesDocsUnauthorized handles this case with default header values.

Unauthorized - An invalid element token, user secret and/or org secret provided
*/
type GetInstancesDocsUnauthorized struct {
}

func (o *GetInstancesDocsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /instances/docs][%d] getInstancesDocsUnauthorized ", 401)
}

func (o *GetInstancesDocsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesDocsForbidden creates a GetInstancesDocsForbidden with default headers values
func NewGetInstancesDocsForbidden() *GetInstancesDocsForbidden {
	return &GetInstancesDocsForbidden{}
}

/*GetInstancesDocsForbidden handles this case with default header values.

Forbidden - Access to the resource by the provider is forbidden
*/
type GetInstancesDocsForbidden struct {
}

func (o *GetInstancesDocsForbidden) Error() string {
	return fmt.Sprintf("[GET /instances/docs][%d] getInstancesDocsForbidden ", 403)
}

func (o *GetInstancesDocsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesDocsNotFound creates a GetInstancesDocsNotFound with default headers values
func NewGetInstancesDocsNotFound() *GetInstancesDocsNotFound {
	return &GetInstancesDocsNotFound{}
}

/*GetInstancesDocsNotFound handles this case with default header values.

Not found - The requested resource is not found
*/
type GetInstancesDocsNotFound struct {
}

func (o *GetInstancesDocsNotFound) Error() string {
	return fmt.Sprintf("[GET /instances/docs][%d] getInstancesDocsNotFound ", 404)
}

func (o *GetInstancesDocsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesDocsMethodNotAllowed creates a GetInstancesDocsMethodNotAllowed with default headers values
func NewGetInstancesDocsMethodNotAllowed() *GetInstancesDocsMethodNotAllowed {
	return &GetInstancesDocsMethodNotAllowed{}
}

/*GetInstancesDocsMethodNotAllowed handles this case with default header values.

Method not allowed - Incorrect HTTP verb used, e.g., GET used when POST expected
*/
type GetInstancesDocsMethodNotAllowed struct {
}

func (o *GetInstancesDocsMethodNotAllowed) Error() string {
	return fmt.Sprintf("[GET /instances/docs][%d] getInstancesDocsMethodNotAllowed ", 405)
}

func (o *GetInstancesDocsMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesDocsNotAcceptable creates a GetInstancesDocsNotAcceptable with default headers values
func NewGetInstancesDocsNotAcceptable() *GetInstancesDocsNotAcceptable {
	return &GetInstancesDocsNotAcceptable{}
}

/*GetInstancesDocsNotAcceptable handles this case with default header values.

Not acceptable - The response content type does not match the 'Accept' header value
*/
type GetInstancesDocsNotAcceptable struct {
}

func (o *GetInstancesDocsNotAcceptable) Error() string {
	return fmt.Sprintf("[GET /instances/docs][%d] getInstancesDocsNotAcceptable ", 406)
}

func (o *GetInstancesDocsNotAcceptable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesDocsConflict creates a GetInstancesDocsConflict with default headers values
func NewGetInstancesDocsConflict() *GetInstancesDocsConflict {
	return &GetInstancesDocsConflict{}
}

/*GetInstancesDocsConflict handles this case with default header values.

Conflict - If a resource being created already exists
*/
type GetInstancesDocsConflict struct {
}

func (o *GetInstancesDocsConflict) Error() string {
	return fmt.Sprintf("[GET /instances/docs][%d] getInstancesDocsConflict ", 409)
}

func (o *GetInstancesDocsConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesDocsUnsupportedMediaType creates a GetInstancesDocsUnsupportedMediaType with default headers values
func NewGetInstancesDocsUnsupportedMediaType() *GetInstancesDocsUnsupportedMediaType {
	return &GetInstancesDocsUnsupportedMediaType{}
}

/*GetInstancesDocsUnsupportedMediaType handles this case with default header values.

Unsupported media type - The server cannot handle the requested Content-Type
*/
type GetInstancesDocsUnsupportedMediaType struct {
}

func (o *GetInstancesDocsUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[GET /instances/docs][%d] getInstancesDocsUnsupportedMediaType ", 415)
}

func (o *GetInstancesDocsUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInstancesDocsInternalServerError creates a GetInstancesDocsInternalServerError with default headers values
func NewGetInstancesDocsInternalServerError() *GetInstancesDocsInternalServerError {
	return &GetInstancesDocsInternalServerError{}
}

/*GetInstancesDocsInternalServerError handles this case with default header values.

Server error - Something went wrong on the Cloud Elements server
*/
type GetInstancesDocsInternalServerError struct {
}

func (o *GetInstancesDocsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /instances/docs][%d] getInstancesDocsInternalServerError ", 500)
}

func (o *GetInstancesDocsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
