// Code generated by go-swagger; DO NOT EDIT.

package instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/akrausesap/goexperiments/openconnectors/util/connectorclient/models"
)

// NewReplaceInstancesTraceLogging2Params creates a new ReplaceInstancesTraceLogging2Params object
// with the default values initialized.
func NewReplaceInstancesTraceLogging2Params() *ReplaceInstancesTraceLogging2Params {
	var ()
	return &ReplaceInstancesTraceLogging2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewReplaceInstancesTraceLogging2ParamsWithTimeout creates a new ReplaceInstancesTraceLogging2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewReplaceInstancesTraceLogging2ParamsWithTimeout(timeout time.Duration) *ReplaceInstancesTraceLogging2Params {
	var ()
	return &ReplaceInstancesTraceLogging2Params{

		timeout: timeout,
	}
}

// NewReplaceInstancesTraceLogging2ParamsWithContext creates a new ReplaceInstancesTraceLogging2Params object
// with the default values initialized, and the ability to set a context for a request
func NewReplaceInstancesTraceLogging2ParamsWithContext(ctx context.Context) *ReplaceInstancesTraceLogging2Params {
	var ()
	return &ReplaceInstancesTraceLogging2Params{

		Context: ctx,
	}
}

// NewReplaceInstancesTraceLogging2ParamsWithHTTPClient creates a new ReplaceInstancesTraceLogging2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReplaceInstancesTraceLogging2ParamsWithHTTPClient(client *http.Client) *ReplaceInstancesTraceLogging2Params {
	var ()
	return &ReplaceInstancesTraceLogging2Params{
		HTTPClient: client,
	}
}

/*ReplaceInstancesTraceLogging2Params contains all the parameters to send to the API endpoint
for the replace instances trace logging2 operation typically these are written to a http.Request
*/
type ReplaceInstancesTraceLogging2Params struct {

	/*Authorization
	  The authorization tokens. The format for the header value is 'User &lt;user secret&gt;, Organization &lt;org secret&gt;'

	*/
	Authorization string
	/*Config
	  Optional body containing configuration (e.g. duration) for enabling trace-level logging.

	*/
	Config *models.TraceLoggingConfig
	/*ID
	  The ID of the element instance

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the replace instances trace logging2 params
func (o *ReplaceInstancesTraceLogging2Params) WithTimeout(timeout time.Duration) *ReplaceInstancesTraceLogging2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the replace instances trace logging2 params
func (o *ReplaceInstancesTraceLogging2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the replace instances trace logging2 params
func (o *ReplaceInstancesTraceLogging2Params) WithContext(ctx context.Context) *ReplaceInstancesTraceLogging2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the replace instances trace logging2 params
func (o *ReplaceInstancesTraceLogging2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the replace instances trace logging2 params
func (o *ReplaceInstancesTraceLogging2Params) WithHTTPClient(client *http.Client) *ReplaceInstancesTraceLogging2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the replace instances trace logging2 params
func (o *ReplaceInstancesTraceLogging2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the replace instances trace logging2 params
func (o *ReplaceInstancesTraceLogging2Params) WithAuthorization(authorization string) *ReplaceInstancesTraceLogging2Params {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the replace instances trace logging2 params
func (o *ReplaceInstancesTraceLogging2Params) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithConfig adds the config to the replace instances trace logging2 params
func (o *ReplaceInstancesTraceLogging2Params) WithConfig(config *models.TraceLoggingConfig) *ReplaceInstancesTraceLogging2Params {
	o.SetConfig(config)
	return o
}

// SetConfig adds the config to the replace instances trace logging2 params
func (o *ReplaceInstancesTraceLogging2Params) SetConfig(config *models.TraceLoggingConfig) {
	o.Config = config
}

// WithID adds the id to the replace instances trace logging2 params
func (o *ReplaceInstancesTraceLogging2Params) WithID(id int64) *ReplaceInstancesTraceLogging2Params {
	o.SetID(id)
	return o
}

// SetID adds the id to the replace instances trace logging2 params
func (o *ReplaceInstancesTraceLogging2Params) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ReplaceInstancesTraceLogging2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.Config != nil {
		if err := r.SetBodyParam(o.Config); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
