// Code generated by go-swagger; DO NOT EDIT.

package instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/akrausesap/goexperiments/openconnectors/util/connectorclient/models"
)

// NewReplaceInstancesTraceLoggingParams creates a new ReplaceInstancesTraceLoggingParams object
// with the default values initialized.
func NewReplaceInstancesTraceLoggingParams() *ReplaceInstancesTraceLoggingParams {
	var ()
	return &ReplaceInstancesTraceLoggingParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReplaceInstancesTraceLoggingParamsWithTimeout creates a new ReplaceInstancesTraceLoggingParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReplaceInstancesTraceLoggingParamsWithTimeout(timeout time.Duration) *ReplaceInstancesTraceLoggingParams {
	var ()
	return &ReplaceInstancesTraceLoggingParams{

		timeout: timeout,
	}
}

// NewReplaceInstancesTraceLoggingParamsWithContext creates a new ReplaceInstancesTraceLoggingParams object
// with the default values initialized, and the ability to set a context for a request
func NewReplaceInstancesTraceLoggingParamsWithContext(ctx context.Context) *ReplaceInstancesTraceLoggingParams {
	var ()
	return &ReplaceInstancesTraceLoggingParams{

		Context: ctx,
	}
}

// NewReplaceInstancesTraceLoggingParamsWithHTTPClient creates a new ReplaceInstancesTraceLoggingParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReplaceInstancesTraceLoggingParamsWithHTTPClient(client *http.Client) *ReplaceInstancesTraceLoggingParams {
	var ()
	return &ReplaceInstancesTraceLoggingParams{
		HTTPClient: client,
	}
}

/*ReplaceInstancesTraceLoggingParams contains all the parameters to send to the API endpoint
for the replace instances trace logging operation typically these are written to a http.Request
*/
type ReplaceInstancesTraceLoggingParams struct {

	/*Authorization
	  The authorization tokens. The format for the header value is 'User &lt;user secret&gt;, Organization &lt;org secret&gt;, Element &lt;token&gt;'

	*/
	Authorization string
	/*Config
	  Optional body containing configuration (e.g. duration) for enabling trace-level logging.

	*/
	Config *models.TraceLoggingConfig

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the replace instances trace logging params
func (o *ReplaceInstancesTraceLoggingParams) WithTimeout(timeout time.Duration) *ReplaceInstancesTraceLoggingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the replace instances trace logging params
func (o *ReplaceInstancesTraceLoggingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the replace instances trace logging params
func (o *ReplaceInstancesTraceLoggingParams) WithContext(ctx context.Context) *ReplaceInstancesTraceLoggingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the replace instances trace logging params
func (o *ReplaceInstancesTraceLoggingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the replace instances trace logging params
func (o *ReplaceInstancesTraceLoggingParams) WithHTTPClient(client *http.Client) *ReplaceInstancesTraceLoggingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the replace instances trace logging params
func (o *ReplaceInstancesTraceLoggingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the replace instances trace logging params
func (o *ReplaceInstancesTraceLoggingParams) WithAuthorization(authorization string) *ReplaceInstancesTraceLoggingParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the replace instances trace logging params
func (o *ReplaceInstancesTraceLoggingParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithConfig adds the config to the replace instances trace logging params
func (o *ReplaceInstancesTraceLoggingParams) WithConfig(config *models.TraceLoggingConfig) *ReplaceInstancesTraceLoggingParams {
	o.SetConfig(config)
	return o
}

// SetConfig adds the config to the replace instances trace logging params
func (o *ReplaceInstancesTraceLoggingParams) SetConfig(config *models.TraceLoggingConfig) {
	o.Config = config
}

// WriteToRequest writes these params to a swagger request
func (o *ReplaceInstancesTraceLoggingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.Config != nil {
		if err := r.SetBodyParam(o.Config); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
