// Code generated by go-swagger; DO NOT EDIT.

package instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/akrausesap/goexperiments/openconnectors/util/connectorclient/models"
)

// NewReplaceInstancesObjectsObjectNameDefinitions2Params creates a new ReplaceInstancesObjectsObjectNameDefinitions2Params object
// with the default values initialized.
func NewReplaceInstancesObjectsObjectNameDefinitions2Params() *ReplaceInstancesObjectsObjectNameDefinitions2Params {
	var ()
	return &ReplaceInstancesObjectsObjectNameDefinitions2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewReplaceInstancesObjectsObjectNameDefinitions2ParamsWithTimeout creates a new ReplaceInstancesObjectsObjectNameDefinitions2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewReplaceInstancesObjectsObjectNameDefinitions2ParamsWithTimeout(timeout time.Duration) *ReplaceInstancesObjectsObjectNameDefinitions2Params {
	var ()
	return &ReplaceInstancesObjectsObjectNameDefinitions2Params{

		timeout: timeout,
	}
}

// NewReplaceInstancesObjectsObjectNameDefinitions2ParamsWithContext creates a new ReplaceInstancesObjectsObjectNameDefinitions2Params object
// with the default values initialized, and the ability to set a context for a request
func NewReplaceInstancesObjectsObjectNameDefinitions2ParamsWithContext(ctx context.Context) *ReplaceInstancesObjectsObjectNameDefinitions2Params {
	var ()
	return &ReplaceInstancesObjectsObjectNameDefinitions2Params{

		Context: ctx,
	}
}

// NewReplaceInstancesObjectsObjectNameDefinitions2ParamsWithHTTPClient creates a new ReplaceInstancesObjectsObjectNameDefinitions2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReplaceInstancesObjectsObjectNameDefinitions2ParamsWithHTTPClient(client *http.Client) *ReplaceInstancesObjectsObjectNameDefinitions2Params {
	var ()
	return &ReplaceInstancesObjectsObjectNameDefinitions2Params{
		HTTPClient: client,
	}
}

/*ReplaceInstancesObjectsObjectNameDefinitions2Params contains all the parameters to send to the API endpoint
for the replace instances objects object name definitions2 operation typically these are written to a http.Request
*/
type ReplaceInstancesObjectsObjectNameDefinitions2Params struct {

	/*Authorization
	  The authorization tokens. The format for the header value is 'User &lt;user secret&gt;, Organization &lt;org secret&gt;'

	*/
	Authorization string
	/*Body
	  The object definition

	*/
	Body *models.Definition
	/*ID
	  The ID of the instance

	*/
	ID int64
	/*ObjectName
	  The name of the object

	*/
	ObjectName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the replace instances objects object name definitions2 params
func (o *ReplaceInstancesObjectsObjectNameDefinitions2Params) WithTimeout(timeout time.Duration) *ReplaceInstancesObjectsObjectNameDefinitions2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the replace instances objects object name definitions2 params
func (o *ReplaceInstancesObjectsObjectNameDefinitions2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the replace instances objects object name definitions2 params
func (o *ReplaceInstancesObjectsObjectNameDefinitions2Params) WithContext(ctx context.Context) *ReplaceInstancesObjectsObjectNameDefinitions2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the replace instances objects object name definitions2 params
func (o *ReplaceInstancesObjectsObjectNameDefinitions2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the replace instances objects object name definitions2 params
func (o *ReplaceInstancesObjectsObjectNameDefinitions2Params) WithHTTPClient(client *http.Client) *ReplaceInstancesObjectsObjectNameDefinitions2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the replace instances objects object name definitions2 params
func (o *ReplaceInstancesObjectsObjectNameDefinitions2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the replace instances objects object name definitions2 params
func (o *ReplaceInstancesObjectsObjectNameDefinitions2Params) WithAuthorization(authorization string) *ReplaceInstancesObjectsObjectNameDefinitions2Params {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the replace instances objects object name definitions2 params
func (o *ReplaceInstancesObjectsObjectNameDefinitions2Params) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBody adds the body to the replace instances objects object name definitions2 params
func (o *ReplaceInstancesObjectsObjectNameDefinitions2Params) WithBody(body *models.Definition) *ReplaceInstancesObjectsObjectNameDefinitions2Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the replace instances objects object name definitions2 params
func (o *ReplaceInstancesObjectsObjectNameDefinitions2Params) SetBody(body *models.Definition) {
	o.Body = body
}

// WithID adds the id to the replace instances objects object name definitions2 params
func (o *ReplaceInstancesObjectsObjectNameDefinitions2Params) WithID(id int64) *ReplaceInstancesObjectsObjectNameDefinitions2Params {
	o.SetID(id)
	return o
}

// SetID adds the id to the replace instances objects object name definitions2 params
func (o *ReplaceInstancesObjectsObjectNameDefinitions2Params) SetID(id int64) {
	o.ID = id
}

// WithObjectName adds the objectName to the replace instances objects object name definitions2 params
func (o *ReplaceInstancesObjectsObjectNameDefinitions2Params) WithObjectName(objectName string) *ReplaceInstancesObjectsObjectNameDefinitions2Params {
	o.SetObjectName(objectName)
	return o
}

// SetObjectName adds the objectName to the replace instances objects object name definitions2 params
func (o *ReplaceInstancesObjectsObjectNameDefinitions2Params) SetObjectName(objectName string) {
	o.ObjectName = objectName
}

// WriteToRequest writes these params to a swagger request
func (o *ReplaceInstancesObjectsObjectNameDefinitions2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// path param objectName
	if err := r.SetPathParam("objectName", o.ObjectName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
