// Code generated by go-swagger; DO NOT EDIT.

package instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/akrausesap/goexperiments/openconnectors/util/connectorclient/models"
)

// NewReplaceInstanceByIDParams creates a new ReplaceInstanceByIDParams object
// with the default values initialized.
func NewReplaceInstanceByIDParams() *ReplaceInstanceByIDParams {
	var ()
	return &ReplaceInstanceByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReplaceInstanceByIDParamsWithTimeout creates a new ReplaceInstanceByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReplaceInstanceByIDParamsWithTimeout(timeout time.Duration) *ReplaceInstanceByIDParams {
	var ()
	return &ReplaceInstanceByIDParams{

		timeout: timeout,
	}
}

// NewReplaceInstanceByIDParamsWithContext creates a new ReplaceInstanceByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewReplaceInstanceByIDParamsWithContext(ctx context.Context) *ReplaceInstanceByIDParams {
	var ()
	return &ReplaceInstanceByIDParams{

		Context: ctx,
	}
}

// NewReplaceInstanceByIDParamsWithHTTPClient creates a new ReplaceInstanceByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReplaceInstanceByIDParamsWithHTTPClient(client *http.Client) *ReplaceInstanceByIDParams {
	var ()
	return &ReplaceInstanceByIDParams{
		HTTPClient: client,
	}
}

/*ReplaceInstanceByIDParams contains all the parameters to send to the API endpoint
for the replace instance by Id operation typically these are written to a http.Request
*/
type ReplaceInstanceByIDParams struct {

	/*Authorization
	  The authorization tokens. The format for the header value is 'User &lt;user secret&gt;, Organization &lt;org secret&gt;'

	*/
	Authorization string
	/*ElementInstance
	  The fields of the element instance to update

	*/
	ElementInstance *models.ElementInstance
	/*ID
	  The ID of the element instance

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the replace instance by Id params
func (o *ReplaceInstanceByIDParams) WithTimeout(timeout time.Duration) *ReplaceInstanceByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the replace instance by Id params
func (o *ReplaceInstanceByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the replace instance by Id params
func (o *ReplaceInstanceByIDParams) WithContext(ctx context.Context) *ReplaceInstanceByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the replace instance by Id params
func (o *ReplaceInstanceByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the replace instance by Id params
func (o *ReplaceInstanceByIDParams) WithHTTPClient(client *http.Client) *ReplaceInstanceByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the replace instance by Id params
func (o *ReplaceInstanceByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the replace instance by Id params
func (o *ReplaceInstanceByIDParams) WithAuthorization(authorization string) *ReplaceInstanceByIDParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the replace instance by Id params
func (o *ReplaceInstanceByIDParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithElementInstance adds the elementInstance to the replace instance by Id params
func (o *ReplaceInstanceByIDParams) WithElementInstance(elementInstance *models.ElementInstance) *ReplaceInstanceByIDParams {
	o.SetElementInstance(elementInstance)
	return o
}

// SetElementInstance adds the elementInstance to the replace instance by Id params
func (o *ReplaceInstanceByIDParams) SetElementInstance(elementInstance *models.ElementInstance) {
	o.ElementInstance = elementInstance
}

// WithID adds the id to the replace instance by Id params
func (o *ReplaceInstanceByIDParams) WithID(id int64) *ReplaceInstanceByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the replace instance by Id params
func (o *ReplaceInstanceByIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ReplaceInstanceByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.ElementInstance != nil {
		if err := r.SetBodyParam(o.ElementInstance); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
