// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/akrausesap/goexperiments/openconnectors/util/registryclient/models"
)

// NewV1MetadataServicesByServiceIDPutParams creates a new V1MetadataServicesByServiceIDPutParams object
// with the default values initialized.
func NewV1MetadataServicesByServiceIDPutParams() *V1MetadataServicesByServiceIDPutParams {
	var ()
	return &V1MetadataServicesByServiceIDPutParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1MetadataServicesByServiceIDPutParamsWithTimeout creates a new V1MetadataServicesByServiceIDPutParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1MetadataServicesByServiceIDPutParamsWithTimeout(timeout time.Duration) *V1MetadataServicesByServiceIDPutParams {
	var ()
	return &V1MetadataServicesByServiceIDPutParams{

		timeout: timeout,
	}
}

// NewV1MetadataServicesByServiceIDPutParamsWithContext creates a new V1MetadataServicesByServiceIDPutParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1MetadataServicesByServiceIDPutParamsWithContext(ctx context.Context) *V1MetadataServicesByServiceIDPutParams {
	var ()
	return &V1MetadataServicesByServiceIDPutParams{

		Context: ctx,
	}
}

// NewV1MetadataServicesByServiceIDPutParamsWithHTTPClient creates a new V1MetadataServicesByServiceIDPutParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1MetadataServicesByServiceIDPutParamsWithHTTPClient(client *http.Client) *V1MetadataServicesByServiceIDPutParams {
	var ()
	return &V1MetadataServicesByServiceIDPutParams{
		HTTPClient: client,
	}
}

/*V1MetadataServicesByServiceIDPutParams contains all the parameters to send to the API endpoint
for the v1 metadata services by service Id put operation typically these are written to a http.Request
*/
type V1MetadataServicesByServiceIDPutParams struct {

	/*Body
	  Service object to be stored

	*/
	Body *models.ServiceUpdate
	/*ServiceID
	  ID of a service

	*/
	ServiceID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 metadata services by service Id put params
func (o *V1MetadataServicesByServiceIDPutParams) WithTimeout(timeout time.Duration) *V1MetadataServicesByServiceIDPutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 metadata services by service Id put params
func (o *V1MetadataServicesByServiceIDPutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 metadata services by service Id put params
func (o *V1MetadataServicesByServiceIDPutParams) WithContext(ctx context.Context) *V1MetadataServicesByServiceIDPutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 metadata services by service Id put params
func (o *V1MetadataServicesByServiceIDPutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 metadata services by service Id put params
func (o *V1MetadataServicesByServiceIDPutParams) WithHTTPClient(client *http.Client) *V1MetadataServicesByServiceIDPutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 metadata services by service Id put params
func (o *V1MetadataServicesByServiceIDPutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the v1 metadata services by service Id put params
func (o *V1MetadataServicesByServiceIDPutParams) WithBody(body *models.ServiceUpdate) *V1MetadataServicesByServiceIDPutParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the v1 metadata services by service Id put params
func (o *V1MetadataServicesByServiceIDPutParams) SetBody(body *models.ServiceUpdate) {
	o.Body = body
}

// WithServiceID adds the serviceID to the v1 metadata services by service Id put params
func (o *V1MetadataServicesByServiceIDPutParams) WithServiceID(serviceID strfmt.UUID) *V1MetadataServicesByServiceIDPutParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the v1 metadata services by service Id put params
func (o *V1MetadataServicesByServiceIDPutParams) SetServiceID(serviceID strfmt.UUID) {
	o.ServiceID = serviceID
}

// WriteToRequest writes these params to a swagger request
func (o *V1MetadataServicesByServiceIDPutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param serviceId
	if err := r.SetPathParam("serviceId", o.ServiceID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
