apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  creationTimestamp: "2019-05-02T06:46:12Z"
  generation: 1
  name: applications.applicationconnector.kyma-project.io
  resourceVersion: "7726"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/applications.applicationconnector.kyma-project.io
  uid: f96cf980-6ca5-11e9-bbec-42010a84018a
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    name: Age
    type: date
  group: applicationconnector.kyma-project.io
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    shortNames:
    - app
    singular: application
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            accessLabel:
              maxLength: 63
              pattern: ^([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]$
              type: string
            services:
              items:
                properties:
                  description:
                    type: string
                  displayName:
                    type: string
                  entries:
                    items:
                      properties:
                        accessLabel:
                          maxLength: 63
                          pattern: ^([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]$
                          type: string
                        credentials:
                          properties:
                            authenticationUrl:
                              type: string
                            csrfInfo:
                              properties:
                                tokenEndpointURL:
                                  type: string
                              required:
                              - tokenEndpointURL
                              type: object
                            secretName:
                              type: string
                            type:
                              type: string
                          required:
                          - type
                          - secretName
                          type: object
                        gatewayUrl:
                          type: string
                        targetUrl:
                          type: string
                        type:
                          enum:
                          - API
                          - Events
                          type: string
                      required:
                      - type
                      type: object
                    type: array
                  id:
                    type: string
                  identifier:
                    type: string
                  longDescription:
                    type: string
                  name:
                    type: string
                  providerDisplayName:
                    type: string
                  tags:
                    items:
                      type: string
                    type: array
                required:
                - id
                - name
                - displayName
                - providerDisplayName
                - description
                - entries
                type: object
              type: array
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: Application
    listKind: ApplicationList
    plural: applications
    shortNames:
    - app
    singular: application
  conditions:
  - lastTransitionTime: "2019-05-02T06:46:12Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
