// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewV1HealthGetParams creates a new V1HealthGetParams object
// with the default values initialized.
func NewV1HealthGetParams() *V1HealthGetParams {

	return &V1HealthGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewV1HealthGetParamsWithTimeout creates a new V1HealthGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewV1HealthGetParamsWithTimeout(timeout time.Duration) *V1HealthGetParams {

	return &V1HealthGetParams{

		timeout: timeout,
	}
}

// NewV1HealthGetParamsWithContext creates a new V1HealthGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewV1HealthGetParamsWithContext(ctx context.Context) *V1HealthGetParams {

	return &V1HealthGetParams{

		Context: ctx,
	}
}

// NewV1HealthGetParamsWithHTTPClient creates a new V1HealthGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewV1HealthGetParamsWithHTTPClient(client *http.Client) *V1HealthGetParams {

	return &V1HealthGetParams{
		HTTPClient: client,
	}
}

/*V1HealthGetParams contains all the parameters to send to the API endpoint
for the v1 health get operation typically these are written to a http.Request
*/
type V1HealthGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the v1 health get params
func (o *V1HealthGetParams) WithTimeout(timeout time.Duration) *V1HealthGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 health get params
func (o *V1HealthGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 health get params
func (o *V1HealthGetParams) WithContext(ctx context.Context) *V1HealthGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 health get params
func (o *V1HealthGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 health get params
func (o *V1HealthGetParams) WithHTTPClient(client *http.Client) *V1HealthGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 health get params
func (o *V1HealthGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *V1HealthGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
