// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// V1HealthGetReader is a Reader for the V1HealthGet structure.
type V1HealthGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1HealthGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewV1HealthGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewV1HealthGetOK creates a V1HealthGetOK with default headers values
func NewV1HealthGetOK() *V1HealthGetOK {
	return &V1HealthGetOK{}
}

/*V1HealthGetOK handles this case with default header values.

The service is in a good health
*/
type V1HealthGetOK struct {
}

func (o *V1HealthGetOK) Error() string {
	return fmt.Sprintf("[GET /v1/health][%d] v1HealthGetOK ", 200)
}

func (o *V1HealthGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
